# Generated by Django 3.2.16 on 2024-02-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
